CREATE (:`Lesson` {`abstract`:"A video clip lesson learned on the topic of Process Control. Actuators inside the tail enable the rudder speed brake panels to steer and slow the Space Shuttle during descent and landing. Unusual wear was found on the planet gears of the actuators during an inspection. This led to a discovery that when the Shuttle was built the gears were installed incorrectly� a critical flight failure mode. The installation error stemmed from the near identical appearance of component gears that had different design topographies. The robust actuators were able to operate for 20 years (approximately 30 missions) without failure. The mistake was not found sooner because the actuators were certified for the original flight life of the Shuttle� 10 years or 100 missions. New gears were installed, and a process control was implemented that accommodates the demands of ground operations. A dedicated fixture was fabricated for each actuator with physical features that prevent installation of the incorrect gear. Designs should be mistake-proofed so that components cannot be assembled incorrectly.
\n<br/>
\n<br/>This 4-minute, 33-second video is a product of the Space Shuttle Program and its Process Control Focus Group.", `day`:28, `lesson`:"Unless mechanical designs are mistake-proofed to prevent incorrect assembly, an assembly error that is not clearly evident from initial inspection may cause a critical flight failure.", `month`:4, `name`:1760, `org`:"Exploration Systems, ", `safety`:"TRUE", `title`:"Process Control to Prevent Incorrect Assembly (Video Lesson)", `url`:"https://nen.nasa.gov/web/11/viewall/-/viewall/1760", `year`:2006});
CREATE (:`Tag`:`NER_O` {`id`:"enable_en", `language`:"en", `ne`:["O"], `pos`:["VBP"], `value`:"enable"});
CREATE (:`Tag`:`NER_Number`:`NER_Percent` {`id`:"100_en", `language`:"en", `ne`:["NUMBER"], `value`:"100"});
CREATE (:`Tag`:`NER_O` {`id`:"appearance_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"appearance"});
CREATE (:`Tag`:`NER_O` {`id`:"wear_en", `language`:"en", `ne`:["O"], `pos`:["VBG"], `value`:"wear"});
CREATE (:`Tag`:`NER_O` {`id`:"original_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"original"});
CREATE (:`Tag`:`NER_O` {`id`:"build_en", `language`:"en", `ne`:["O"], `pos`:["VB"], `value`:"build"});
CREATE (:`Tag`:`NER_O` {`id`:"physical_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"physical"});
CREATE (:`Tag`:`NER_O` {`id`:"incorrectly_en", `language`:"en", `ne`:["O"], `pos`:["RB"], `value`:"incorrectly"});
CREATE (:`Tag`:`NER_O` {`id`:"assemble_en", `language`:"en", `ne`:["O"], `pos`:["VBG"], `value`:"assemble"});
CREATE (:`Tag`:`NER_O` {`id`:"without_en", `language`:"en", `ne`:["O"], `pos`:["IN"], `value`:"without"});
CREATE (:`Tag`:`NER_O` {`id`:"space_en", `language`:"en", `ne`:["O"], `pos`:["NNP"], `value`:"space"});
CREATE (:`Tag`:`NER_O` {`id`:"descent_en", `language`:"en", `ne`:["O"], `pos`:["NNP"], `value`:"descent"});
CREATE (:`Tag`:`NER_O` {`id`:"mission_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"mission"});
CREATE (:`Tag`:`NER_O` {`id`:"program_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"program"});
CREATE (:`Tag`:`NER_O` {`id`:"component_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"component"});
CREATE (:`Tag`:`NER_O` {`id`:"assembly_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"assembly"});
CREATE (:`Tag`:`NER_O` {`id`:"different_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"different"});
CREATE (:`Tag`:`NER_O` {`id`:"control_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"control"});
CREATE (:`Tag`:`NER_O` {`id`:"topic_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"topic"});
CREATE (:`Tag`:`NER_O` {`id`:"prevent_en", `language`:"en", `ne`:["O"], `pos`:["VB"], `value`:"prevent"});
CREATE (:`Tag`:`NER_O` {`id`:"clearly_en", `language`:"en", `ne`:["O"], `pos`:["RB"], `value`:"clearly"});
CREATE (:`Tag`:`NER_O` {`id`:"life_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"life"});
CREATE (:`Tag`:`NER_O` {`id`:"panel_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"panel"});
CREATE (:`Tag`:`NER_O` {`id`:"feature_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"feature"});
CREATE (:`Tag`:`NER_O` {`id`:"certify_en", `language`:"en", `ne`:["O"], `pos`:["VB"], `value`:"certify"});
CREATE (:`Tag`:`NER_Duration` {`id`:"20 years_en", `language`:"en", `ne`:["DURATION"], `value`:"20 years"});
CREATE (:`Tag`:`NER_O` {`id`:"actuator_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"actuator"});
CREATE (:`Tag`:`NER_O` {`id`:"gear_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"gear"});
CREATE (:`Tag`:`NER_O` {`id`:"dedicated_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"dedicated"});
CREATE (:`Tag`:`NER_O` {`id`:"incorrect_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"incorrect"});
CREATE (:`Tag`:`NER_O` {`id`:"fixture_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"fixture"});
CREATE (:`Tag`:`NER_O` {`id`:"steer_en", `language`:"en", `ne`:["O"], `pos`:["VBG"], `value`:"steer"});
CREATE (:`Tag`:`NER_O` {`id`:"identical_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"identical"});
CREATE (:`Tag`:`NER_O` {`id`:"fabricate_en", `language`:"en", `ne`:["O"], `pos`:["VBN"], `value`:"fabricate"});
CREATE (:`Tag`:`NER_O` {`id`:"clip_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"clip"});
CREATE (:`Tag`:`NER_Organization` {`id`:"Process Control Focus Group_en", `language`:"en", `ne`:["ORGANIZATION"], `value`:"Process Control Focus Group"});
CREATE (:`AnnotatedText`:`UNIQUE IMPORT LABEL` {`id`:1760, `numTerms`:121, `UNIQUE IMPORT ID`:153113});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"ed01a3dd13f95923c80efe1e5494af58", `id`:"1760_0", `sentenceNumber`:0, `text`:"A video clip lesson learned on the topic of Process Control.", `UNIQUE IMPORT ID`:153114});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:7, `startPosition`:2, `UNIQUE IMPORT ID`:153115});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:40, `startPosition`:35, `UNIQUE IMPORT ID`:153116});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:27, `startPosition`:20, `UNIQUE IMPORT ID`:153117});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:59, `startPosition`:52, `UNIQUE IMPORT ID`:153118});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:12, `startPosition`:8, `UNIQUE IMPORT ID`:153119});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:51, `startPosition`:44, `UNIQUE IMPORT ID`:153120});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:19, `startPosition`:13, `UNIQUE IMPORT ID`:153121});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"52dd4f4c956ac0b62e2ec8aaa1df3c5e", `id`:"1760_1", `sentenceNumber`:1, `text`:"Actuators inside the tail enable the rudder speed brake panels to steer and slow the Space Shuttle during descent and landing.", `UNIQUE IMPORT ID`:153122});
CREATE (:`Tag`:`NER_O` {`id`:"slow_en", `language`:"en", `ne`:["O"], `pos`:["VB"], `value`:"slow"});
CREATE (:`Tag`:`NER_O` {`id`:"rudder_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"rudder"});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:104, `startPosition`:98, `UNIQUE IMPORT ID`:153125});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:77, `startPosition`:71, `UNIQUE IMPORT ID`:153126});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:174, `startPosition`:167, `UNIQUE IMPORT ID`:153127});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:110, `startPosition`:105, `UNIQUE IMPORT ID`:153128});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:141, `startPosition`:137, `UNIQUE IMPORT ID`:153129});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:116, `startPosition`:111, `UNIQUE IMPORT ID`:153130});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:86, `startPosition`:82, `UNIQUE IMPORT ID`:153131});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:151, `startPosition`:146, `UNIQUE IMPORT ID`:153132});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:186, `startPosition`:179, `UNIQUE IMPORT ID`:153133});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:123, `startPosition`:117, `UNIQUE IMPORT ID`:153134});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:93, `startPosition`:87, `UNIQUE IMPORT ID`:153135});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:159, `startPosition`:152, `UNIQUE IMPORT ID`:153136});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:70, `startPosition`:61, `UNIQUE IMPORT ID`:153137});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:132, `startPosition`:127, `UNIQUE IMPORT ID`:153138});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"fc30b97433f04eaf16e9ffe9994ddc10", `id`:"1760_2", `sentenceNumber`:2, `text`:"Unusual wear was found on the planet gears of the actuators during an inspection.", `UNIQUE IMPORT ID`:153139});
CREATE (:`Tag`:`NER_O` {`id`:"planet_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"planet"});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:230, `startPosition`:225, `UNIQUE IMPORT ID`:153141});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:268, `startPosition`:258, `UNIQUE IMPORT ID`:153142});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:200, `startPosition`:196, `UNIQUE IMPORT ID`:153143});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:224, `startPosition`:218, `UNIQUE IMPORT ID`:153144});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:195, `startPosition`:188, `UNIQUE IMPORT ID`:153145});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:210, `startPosition`:205, `UNIQUE IMPORT ID`:153146});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:247, `startPosition`:238, `UNIQUE IMPORT ID`:153147});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"f837472ea925a1e85554429612a8bc24", `id`:"1760_3", `sentenceNumber`:3, `text`:"This led to a discovery that when the Shuttle was built the gears were installed incorrectly� a critical flight failure mode.", `UNIQUE IMPORT ID`:153148});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:325, `startPosition`:320, `UNIQUE IMPORT ID`:153149});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:278, `startPosition`:275, `UNIQUE IMPORT ID`:153150});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:315, `startPosition`:308, `UNIQUE IMPORT ID`:153151});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:350, `startPosition`:341, `UNIQUE IMPORT ID`:153152});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:394, `startPosition`:390, `UNIQUE IMPORT ID`:153153});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:381, `startPosition`:375, `UNIQUE IMPORT ID`:153154});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:335, `startPosition`:330, `UNIQUE IMPORT ID`:153155});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:293, `startPosition`:284, `UNIQUE IMPORT ID`:153156});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:374, `startPosition`:366, `UNIQUE IMPORT ID`:153157});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:389, `startPosition`:382, `UNIQUE IMPORT ID`:153158});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:362, `startPosition`:351, `UNIQUE IMPORT ID`:153159});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"aae7f1d2f3cf3d0b64b31228f101c62e", `id`:"1760_4", `sentenceNumber`:4, `text`:"The installation error stemmed from the near identical appearance of component gears that had different design topographies.", `UNIQUE IMPORT ID`:153160});
CREATE (:`Tag`:`NER_O` {`id`:"topography_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"topography"});
CREATE (:`Tag`:`NER_O` {`id`:"stem_en", `language`:"en", `ne`:["O"], `pos`:["VBD"], `value`:"stem"});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:412, `startPosition`:400, `UNIQUE IMPORT ID`:153163});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:474, `startPosition`:465, `UNIQUE IMPORT ID`:153164});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:426, `startPosition`:419, `UNIQUE IMPORT ID`:153165});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:461, `startPosition`:451, `UNIQUE IMPORT ID`:153166});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:440, `startPosition`:436, `UNIQUE IMPORT ID`:153167});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:506, `startPosition`:500, `UNIQUE IMPORT ID`:153168});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:450, `startPosition`:441, `UNIQUE IMPORT ID`:153169});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:499, `startPosition`:490, `UNIQUE IMPORT ID`:153170});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:480, `startPosition`:475, `UNIQUE IMPORT ID`:153171});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:519, `startPosition`:507, `UNIQUE IMPORT ID`:153172});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:418, `startPosition`:413, `UNIQUE IMPORT ID`:153173});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"029cd95e68e4eb700eed19b34877130c", `id`:"1760_5", `sentenceNumber`:5, `text`:"The robust actuators were able to operate for 20 years (approximately 30 missions) without failure.", `UNIQUE IMPORT ID`:153174});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:590, `startPosition`:577, `UNIQUE IMPORT ID`:153175});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:602, `startPosition`:594, `UNIQUE IMPORT ID`:153176});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:551, `startPosition`:547, `UNIQUE IMPORT ID`:153177});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:541, `startPosition`:532, `UNIQUE IMPORT ID`:153178});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:619, `startPosition`:612, `UNIQUE IMPORT ID`:153179});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:575, `startPosition`:567, `UNIQUE IMPORT ID`:153180});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:562, `startPosition`:555, `UNIQUE IMPORT ID`:153181});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:611, `startPosition`:604, `UNIQUE IMPORT ID`:153182});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:531, `startPosition`:525, `UNIQUE IMPORT ID`:153183});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:593, `startPosition`:591, `UNIQUE IMPORT ID`:153184});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"c49089643027056be056f7d2edb57340", `id`:"1760_6", `sentenceNumber`:6, `text`:"The mistake was not found sooner because the actuators were certified for the original flight life of the Shuttle� 10 years or 100 missions.", `UNIQUE IMPORT ID`:153185});
CREATE (:`Tag`:`NER_Duration` {`id`:"10 years_en", `language`:"en", `ne`:["DURATION"], `value`:"10 years"});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:744, `startPosition`:736, `UNIQUE IMPORT ID`:153187});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:760, `startPosition`:752, `UNIQUE IMPORT ID`:153188});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:632, `startPosition`:625, `UNIQUE IMPORT ID`:153189});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:646, `startPosition`:641, `UNIQUE IMPORT ID`:153190});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:714, `startPosition`:708, `UNIQUE IMPORT ID`:153191});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:653, `startPosition`:647, `UNIQUE IMPORT ID`:153192});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:734, `startPosition`:727, `UNIQUE IMPORT ID`:153193});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:690, `startPosition`:681, `UNIQUE IMPORT ID`:153194});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:675, `startPosition`:666, `UNIQUE IMPORT ID`:153195});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:707, `startPosition`:699, `UNIQUE IMPORT ID`:153196});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:719, `startPosition`:715, `UNIQUE IMPORT ID`:153197});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:751, `startPosition`:748, `UNIQUE IMPORT ID`:153198});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"a23536753124f9fd97e244e37e2d0032", `id`:"1760_7", `sentenceNumber`:7, `text`:"New gears were installed, and a process control was implemented that accommodates the demands of ground operations.", `UNIQUE IMPORT ID`:153199});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:855, `startPosition`:848, `UNIQUE IMPORT ID`:153200});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:809, `startPosition`:802, `UNIQUE IMPORT ID`:153201});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:876, `startPosition`:866, `UNIQUE IMPORT ID`:153202});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:786, `startPosition`:777, `UNIQUE IMPORT ID`:153203});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:765, `startPosition`:762, `UNIQUE IMPORT ID`:153204});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:801, `startPosition`:794, `UNIQUE IMPORT ID`:153205});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:865, `startPosition`:859, `UNIQUE IMPORT ID`:153206});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:771, `startPosition`:766, `UNIQUE IMPORT ID`:153207});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:825, `startPosition`:814, `UNIQUE IMPORT ID`:153208});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:843, `startPosition`:831, `UNIQUE IMPORT ID`:153209});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"10929d5ad55baf527edbdc3235761dc9", `id`:"1760_8", `sentenceNumber`:8, `text`:"A dedicated fixture was fabricated for each actuator with physical features that prevent installation of the incorrect gear.", `UNIQUE IMPORT ID`:153210});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:889, `startPosition`:880, `UNIQUE IMPORT ID`:153211});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:953, `startPosition`:945, `UNIQUE IMPORT ID`:153212});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1001, `startPosition`:997, `UNIQUE IMPORT ID`:153213});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:912, `startPosition`:902, `UNIQUE IMPORT ID`:153214});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:979, `startPosition`:967, `UNIQUE IMPORT ID`:153215});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:944, `startPosition`:936, `UNIQUE IMPORT ID`:153216});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:897, `startPosition`:890, `UNIQUE IMPORT ID`:153217});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:930, `startPosition`:922, `UNIQUE IMPORT ID`:153218});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:996, `startPosition`:987, `UNIQUE IMPORT ID`:153219});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:966, `startPosition`:959, `UNIQUE IMPORT ID`:153220});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"d927275c3d2e9a72af4387313492d401", `id`:"1760_9", `sentenceNumber`:9, `text`:"Designs should be mistake-proofed so that components cannot be assembled incorrectly.", `UNIQUE IMPORT ID`:153221});
CREATE (:`Tag`:`NER_O` {`id`:"mistake-proof_en", `language`:"en", `ne`:["O"], `pos`:["VBN"], `value`:"mistake-proof"});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1087, `startPosition`:1076, `UNIQUE IMPORT ID`:153223});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1055, `startPosition`:1045, `UNIQUE IMPORT ID`:153224});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1075, `startPosition`:1066, `UNIQUE IMPORT ID`:153225});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1010, `startPosition`:1003, `UNIQUE IMPORT ID`:153226});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:1036, `startPosition`:1021, `UNIQUE IMPORT ID`:153227});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"bba6b3e3c3e78d4a2016159f7b30fa10", `id`:"1760_10", `sentenceNumber`:10, `text`:"<br/>
\n<br/>This 4-minute, 33-second video is a product of the Space Shuttle Program and its Process Control Focus Group.", `UNIQUE IMPORT ID`:153228});
CREATE (:`Tag`:`NER_Duration` {`id`:"33-second_en", `language`:"en", `ne`:["DURATION"], `value`:"33-second"});
CREATE (:`Tag`:`NER_Date` {`id`:"This 4-minute_en", `language`:"en", `ne`:["DATE"], `value`:"This 4-minute"});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1158, `startPosition`:1153, `UNIQUE IMPORT ID`:153231});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:1145, `startPosition`:1138, `UNIQUE IMPORT ID`:153232});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1132, `startPosition`:1127, `UNIQUE IMPORT ID`:153233});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1166, `startPosition`:1159, `UNIQUE IMPORT ID`:153234});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1126, `startPosition`:1117, `UNIQUE IMPORT ID`:153235});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1115, `startPosition`:1102, `UNIQUE IMPORT ID`:153236});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1174, `startPosition`:1167, `UNIQUE IMPORT ID`:153237});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1210, `startPosition`:1183, `UNIQUE IMPORT ID`:153238});
CREATE (:`Sentence`:`UNIQUE IMPORT LABEL` {`hash`:"5ebba5b296f8e92fba65fb2a0139cb67", `id`:"1760_12", `sentenceNumber`:12, `text`:"Unless mechanical designs are mistake-proofed to prevent incorrect assembly, an assembly error that is not clearly evident from initial inspection may cause a critical flight failure.", `UNIQUE IMPORT ID`:153240});
CREATE (:`Tag`:`NER_O` {`id`:"mistake-proofed_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"mistake-proofed"});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1288, `startPosition`:1280, `UNIQUE IMPORT ID`:153242});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1230, `startPosition`:1220, `UNIQUE IMPORT ID`:153243});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1359, `startPosition`:1349, `UNIQUE IMPORT ID`:153244});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1387, `startPosition`:1381, `UNIQUE IMPORT ID`:153245});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1327, `startPosition`:1320, `UNIQUE IMPORT ID`:153246});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1395, `startPosition`:1388, `UNIQUE IMPORT ID`:153247});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1301, `startPosition`:1293, `UNIQUE IMPORT ID`:153248});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1269, `startPosition`:1262, `UNIQUE IMPORT ID`:153249});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1238, `startPosition`:1231, `UNIQUE IMPORT ID`:153250});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1335, `startPosition`:1328, `UNIQUE IMPORT ID`:153251});
CREATE (:`TagOccurrence`:`ROOT`:`UNIQUE IMPORT LABEL` {`endPosition`:1369, `startPosition`:1364, `UNIQUE IMPORT ID`:153252});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1279, `startPosition`:1270, `UNIQUE IMPORT ID`:153253});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1307, `startPosition`:1302, `UNIQUE IMPORT ID`:153254});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1258, `startPosition`:1243, `UNIQUE IMPORT ID`:153255});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1380, `startPosition`:1372, `UNIQUE IMPORT ID`:153256});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1219, `startPosition`:1213, `UNIQUE IMPORT ID`:153258});
CREATE (:`TagOccurrence`:`UNIQUE IMPORT LABEL` {`endPosition`:1348, `startPosition`:1341, `UNIQUE IMPORT ID`:153259});
CREATE (:`Tag`:`NER_O` {`id`:"initial_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"initial"});
CREATE (:`Tag`:`NER_O` {`id`:"evident_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"evident"});
CREATE (:`Tag`:`NER_O` {`id`:"sooner_en", `language`:"en", `ne`:["O"], `pos`:["RBR"], `value`:"sooner"});
CREATE (:`Tag`:`NER_O` {`id`:"video_en", `language`:"en", `ne`:["O"], `pos`:["NNP"], `value`:"video"});
CREATE (:`Tag`:`NER_O` {`id`:"mistake_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"mistake"});
CREATE (:`Tag`:`NER_O` {`id`:"robust_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"robust"});
CREATE (:`Tag`:`NER_Misc` {`id`:"Shuttle_en", `language`:"en", `ne`:["MISC"], `value`:"Shuttle"});
CREATE (:`Tag`:`NER_O` {`id`:"near_en", `language`:"en", `ne`:["O"], `pos`:["IN"], `value`:"near"});
CREATE (:`Tag`:`NER_O` {`id`:"accommodate_en", `language`:"en", `ne`:["O"], `pos`:["VB"], `value`:"accommodate"});
CREATE (:`Tag`:`NER_O` {`id`:"speed_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"speed"});
CREATE (:`Tag`:`NER_O` {`id`:"discovery_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"discovery"});
CREATE (:`Tag`:`NER_Number`:`NER_Percent` {`id`:"30_en", `language`:"en", `ne`:["PERCENT"], `value`:"30"});
CREATE (:`Tag`:`NER_O` {`id`:"demand_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"demand"});
CREATE (:`Tag`:`NER_O` {`id`:"mechanical_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"mechanical"});
CREATE (:`Tag`:`NER_O` {`id`:"shuttle_en", `language`:"en", `ne`:["O"], `pos`:["NNP"], `value`:"shuttle"});
CREATE (:`Tag`:`NER_O` {`id`:"product_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"product"});
CREATE (:`Tag`:`NER_O` {`id`:"learn_en", `language`:"en", `ne`:["O"], `pos`:["VBN"], `value`:"learn"});
CREATE (:`Tag`:`NER_O` {`id`:"lead_en", `language`:"en", `ne`:["O"], `pos`:["VBN"], `value`:"lead"});
CREATE (:`Tag`:`NER_O` {`id`:"new_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"new"});
CREATE (:`Tag`:`NER_O` {`id`:"inside_en", `language`:"en", `ne`:["O"], `pos`:["IN"], `value`:"inside"});
CREATE (:`Tag`:`NER_O` {`id`:"lesson_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"lesson"});
CREATE (:`Tag`:`NER_O` {`id`:"able_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"able"});
CREATE (:`Tag`:`NER_O` {`id`:"critical_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"critical"});
CREATE (:`Tag`:`NER_O` {`id`:"landing_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"landing"});
CREATE (:`Tag`:`NER_O` {`id`:"flight_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"flight"});
CREATE (:`Tag`:`NER_O` {`id`:"find_en", `language`:"en", `ne`:["O"], `pos`:["VBD"], `value`:"find"});
CREATE (:`Tag`:`NER_O` {`id`:"mode_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"mode"});
CREATE (:`Tag`:`NER_O` {`id`:"approximately_en", `language`:"en", `ne`:["O"], `pos`:["RB"], `value`:"approximately"});
CREATE (:`Tag`:`NER_O` {`id`:"operate_en", `language`:"en", `ne`:["O"], `pos`:["VBG"], `value`:"operate"});
CREATE (:`Tag`:`NER_O` {`id`:"ground_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"ground"});
CREATE (:`Tag`:`NER_O` {`id`:"process_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"process"});
CREATE (:`Tag`:`NER_O` {`id`:"operation_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"operation"});
CREATE (:`Tag`:`NER_O` {`id`:"error_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"error"});
CREATE (:`Tag`:`NER_O` {`id`:"install_en", `language`:"en", `ne`:["O"], `pos`:["VBN"], `value`:"install"});
CREATE (:`Tag`:`NER_O` {`id`:"failure_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"failure"});
CREATE (:`Tag`:`NER_O` {`id`:"implement_en", `language`:"en", `ne`:["O"], `pos`:["VBG"], `value`:"implement"});
CREATE (:`Tag`:`NER_O` {`id`:"inspection_en", `language`:"en", `ne`:["O"], `pos`:["NNS"], `value`:"inspection"});
CREATE (:`Tag`:`NER_O` {`id`:"installation_en", `language`:"en", `ne`:["O"], `pos`:["NN"], `value`:"installation"});
CREATE (:`Tag`:`NER_O` {`id`:"cause_en", `language`:"en", `ne`:["O"], `pos`:["VBG"], `value`:"cause"});
CREATE (:`Tag`:`NER_O` {`id`:"design_en", `language`:"en", `ne`:["O"], `pos`:["VBN"], `value`:"design"});
CREATE (:`Tag`:`NER_O` {`id`:"brake_en", `language`:"en", `ne`:["O"], `pos`:["NNP"], `value`:"brake"});
CREATE (:`Tag`:`NER_O` {`id`:"tail_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"tail"});
CREATE (:`Tag`:`NER_O` {`id`:"unless_en", `language`:"en", `ne`:["O"], `pos`:["IN"], `value`:"unless"});
CREATE (:`Tag`:`NER_O` {`id`:"unusual_en", `language`:"en", `ne`:["O"], `pos`:["JJ"], `value`:"unusual"});
CREATE INDEX ON :`Tag`(`value`);
CREATE CONSTRAINT ON (node:`Lesson`) ASSERT node.`name` IS UNIQUE;
CREATE CONSTRAINT ON (node:`Tag`) ASSERT node.`id` IS UNIQUE;
CREATE CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT node.`UNIQUE IMPORT ID` IS UNIQUE;
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153114}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153115}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153115}), (n2:`Tag`{`id`:"video_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153114}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153116}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153116}), (n2:`Tag`{`id`:"topic_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153114}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153117}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153117}), (n2:`Tag`{`id`:"learn_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153114}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153118}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153118}), (n2:`Tag`{`id`:"control_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153114}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153119}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153119}), (n2:`Tag`{`id`:"clip_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153114}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153120}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153120}), (n2:`Tag`{`id`:"process_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153114}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153121}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153121}), (n2:`Tag`{`id`:"lesson_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153117}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153117}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153121}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153115}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153121}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153119}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153117}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153121}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153117}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153116}) CREATE (n1)-[r:`NMOD` {`specific`:"on"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153116}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153120}) CREATE (n1)-[r:`ACL` {`specific`:"of"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153120}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153118}) CREATE (n1)-[r:`DOBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153114}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153125}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153125}), (n2:`Tag`{`id`:"rudder_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153126}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153126}), (n2:`Tag`{`id`:"inside_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153127}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153127}), (n2:`Tag`{`id`:"descent_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153128}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153128}), (n2:`Tag`{`id`:"speed_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153129}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153129}), (n2:`Tag`{`id`:"slow_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153130}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153130}), (n2:`Tag`{`id`:"brake_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153131}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153131}), (n2:`Tag`{`id`:"tail_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153132}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153132}), (n2:`Tag`{`id`:"space_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153133}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153133}), (n2:`Tag`{`id`:"landing_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153134}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153134}), (n2:`Tag`{`id`:"panel_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153135}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153135}), (n2:`Tag`{`id`:"enable_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153136}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153136}), (n2:`Tag`{`id`:"shuttle_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153137}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153137}), (n2:`Tag`{`id`:"actuator_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153138}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153138}), (n2:`Tag`{`id`:"steer_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153135}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153135}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153135}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153137}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153131}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153126}) CREATE (n1)-[r:`CASE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153137}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153131}) CREATE (n1)-[r:`NMOD` {`specific`:"inside"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153128}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153125}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153135}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153128}) CREATE (n1)-[r:`DOBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153134}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153130}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153138}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153134}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153129}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153134}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153128}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153138}) CREATE (n1)-[r:`ACL` {`specific`:"to"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153128}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153129}) CREATE (n1)-[r:`ACL` {`specific`:"to"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153138}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153129}) CREATE (n1)-[r:`CONJ` {`specific`:"and"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153136}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153132}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153138}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153136}) CREATE (n1)-[r:`DOBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153138}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153127}) CREATE (n1)-[r:`NMOD` {`specific`:"during"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153138}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153133}) CREATE (n1)-[r:`NMOD` {`specific`:"during"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153127}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153133}) CREATE (n1)-[r:`CONJ` {`specific`:"and"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153122}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153141}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153141}), (n2:`Tag`{`id`:"gear_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153142}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153142}), (n2:`Tag`{`id`:"inspection_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153143}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153143}), (n2:`Tag`{`id`:"wear_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153144}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153144}), (n2:`Tag`{`id`:"planet_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153145}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153145}), (n2:`Tag`{`id`:"unusual_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153146}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153146}), (n2:`Tag`{`id`:"find_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153147}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153147}), (n2:`Tag`{`id`:"actuator_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153146}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153146}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153143}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153145}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153146}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153143}) CREATE (n1)-[r:`NSUBJPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153141}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153144}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153146}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153141}) CREATE (n1)-[r:`NMOD` {`specific`:"on"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153141}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153147}) CREATE (n1)-[r:`NMOD` {`specific`:"of"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153146}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153142}) CREATE (n1)-[r:`NMOD` {`specific`:"during"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153139}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153149}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153149}), (n2:`Tag`{`id`:"build_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153150}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153150}), (n2:`Tag`{`id`:"lead_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153151}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153151}), (n2:`Tag`{`id`:"Shuttle_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153152}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153152}), (n2:`Tag`{`id`:"install_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153153}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153153}), (n2:`Tag`{`id`:"mode_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153154}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153154}), (n2:`Tag`{`id`:"flight_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153155}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153155}), (n2:`Tag`{`id`:"gear_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153156}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153156}), (n2:`Tag`{`id`:"discovery_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153157}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153157}), (n2:`Tag`{`id`:"critical_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153158}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153158}), (n2:`Tag`{`id`:"failure_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153159}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153159}), (n2:`Tag`{`id`:"incorrectly_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153150}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153150}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153150}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153151}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153156}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153151}) CREATE (n1)-[r:`CASE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153156}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153151}) CREATE (n1)-[r:`DET`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153150}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153156}) CREATE (n1)-[r:`NMOD` {`specific`:"to"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153152}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153151}) CREATE (n1)-[r:`DOBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153149}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153151}) CREATE (n1)-[r:`ADVMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153149}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153151}) CREATE (n1)-[r:`NSUBJPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153152}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153149}) CREATE (n1)-[r:`ADVCL`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153152}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153155}) CREATE (n1)-[r:`NSUBJPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153150}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153152}) CREATE (n1)-[r:`CCOMP`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153152}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153159}) CREATE (n1)-[r:`ADVMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153153}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153157}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153153}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153154}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153153}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153158}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153152}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153153}) CREATE (n1)-[r:`DOBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153148}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153163}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153163}), (n2:`Tag`{`id`:"installation_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153164}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153164}), (n2:`Tag`{`id`:"component_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153165}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153165}), (n2:`Tag`{`id`:"stem_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153166}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153166}), (n2:`Tag`{`id`:"appearance_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153167}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153167}), (n2:`Tag`{`id`:"near_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153168}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153168}), (n2:`Tag`{`id`:"design_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153169}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153169}), (n2:`Tag`{`id`:"identical_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153170}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153170}), (n2:`Tag`{`id`:"different_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153171}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153171}), (n2:`Tag`{`id`:"gear_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153172}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153172}), (n2:`Tag`{`id`:"topography_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153173}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153173}), (n2:`Tag`{`id`:"error_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153165}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153165}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153173}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153163}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153165}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153173}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153166}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153167}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153166}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153169}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153165}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153166}) CREATE (n1)-[r:`NMOD` {`specific`:"from"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153171}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153164}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153166}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153171}) CREATE (n1)-[r:`NMOD` {`specific`:"of"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153172}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153170}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153172}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153168}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153160}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153175}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153175}), (n2:`Tag`{`id`:"approximately_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153176}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153176}), (n2:`Tag`{`id`:"mission_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153177}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153177}), (n2:`Tag`{`id`:"able_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153178}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153178}), (n2:`Tag`{`id`:"actuator_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153179}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153179}), (n2:`Tag`{`id`:"failure_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153180}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153180}), (n2:`Tag`{`id`:"20 years_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153181}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153181}), (n2:`Tag`{`id`:"operate_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153182}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153182}), (n2:`Tag`{`id`:"without_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153183}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153183}), (n2:`Tag`{`id`:"robust_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153184}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153184}), (n2:`Tag`{`id`:"30_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153177}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153177}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153178}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153180}) CREATE (n1)-[r:`DET`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153178}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153183}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153177}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153178}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153181}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153178}) CREATE (n1)-[r:`NSUBJ:XSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153177}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153180}) CREATE (n1)-[r:`COP`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153181}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153180}) CREATE (n1)-[r:`MARK`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153177}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153181}) CREATE (n1)-[r:`XCOMP`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153181}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153180}) CREATE (n1)-[r:`NMOD` {`specific`:"for"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153184}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153175}) CREATE (n1)-[r:`ADVMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153176}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153184}) CREATE (n1)-[r:`NUMMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153180}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153176}) CREATE (n1)-[r:`APPOS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153179}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153182}) CREATE (n1)-[r:`CASE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153181}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153179}) CREATE (n1)-[r:`NMOD` {`specific`:"without"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153174}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}), (n2:`Tag`{`id`:"10 years_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153188}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153188}), (n2:`Tag`{`id`:"mission_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153189}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153189}), (n2:`Tag`{`id`:"mistake_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153190}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153190}), (n2:`Tag`{`id`:"find_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153191}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153191}), (n2:`Tag`{`id`:"flight_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153192}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153192}), (n2:`Tag`{`id`:"sooner_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153193}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153193}), (n2:`Tag`{`id`:"shuttle_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153194}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153194}), (n2:`Tag`{`id`:"certify_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153195}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153195}), (n2:`Tag`{`id`:"actuator_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153196}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153196}), (n2:`Tag`{`id`:"original_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153197}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153197}), (n2:`Tag`{`id`:"life_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153198}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153198}), (n2:`Tag`{`id`:"100_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153190}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153190}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153189}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}) CREATE (n1)-[r:`DET`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153190}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153189}) CREATE (n1)-[r:`NSUBJPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153190}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}) CREATE (n1)-[r:`AUXPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153190}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}) CREATE (n1)-[r:`NEG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153190}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153192}) CREATE (n1)-[r:`ADVMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153194}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}) CREATE (n1)-[r:`MARK`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153195}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}) CREATE (n1)-[r:`DET`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153194}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153195}) CREATE (n1)-[r:`NSUBJPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153194}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}) CREATE (n1)-[r:`AUXPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153192}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153194}) CREATE (n1)-[r:`ADVCL` {`specific`:"because"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153197}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}) CREATE (n1)-[r:`CASE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153197}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}) CREATE (n1)-[r:`DET`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153197}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153196}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153197}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153191}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153194}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153197}) CREATE (n1)-[r:`NMOD` {`specific`:"for"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153193}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153197}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}) CREATE (n1)-[r:`NMOD` {`specific`:"of"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153188}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153198}) CREATE (n1)-[r:`NUMMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153197}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153188}) CREATE (n1)-[r:`NMOD` {`specific`:"of"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153187}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153188}) CREATE (n1)-[r:`CONJ` {`specific`:"or"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153185}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153200}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153200}), (n2:`Tag`{`id`:"demand_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153201}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153201}), (n2:`Tag`{`id`:"control_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153202}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153202}), (n2:`Tag`{`id`:"operation_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153203}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153203}), (n2:`Tag`{`id`:"install_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153204}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153204}), (n2:`Tag`{`id`:"new_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153205}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153205}), (n2:`Tag`{`id`:"process_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153206}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153206}), (n2:`Tag`{`id`:"ground_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153207}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153207}), (n2:`Tag`{`id`:"gear_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153208}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153208}), (n2:`Tag`{`id`:"implement_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153209}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153209}), (n2:`Tag`{`id`:"accommodate_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153203}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153203}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153207}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153204}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153203}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153207}) CREATE (n1)-[r:`NSUBJPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153201}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153205}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153208}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153201}) CREATE (n1)-[r:`NSUBJPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153203}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153208}) CREATE (n1)-[r:`CONJ` {`specific`:"and"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153208}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153209}) CREATE (n1)-[r:`CCOMP`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153209}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153200}) CREATE (n1)-[r:`DOBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153202}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153206}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153200}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153202}) CREATE (n1)-[r:`NMOD` {`specific`:"of"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153199}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153211}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153211}), (n2:`Tag`{`id`:"dedicated_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153212}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153212}), (n2:`Tag`{`id`:"feature_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153213}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153213}), (n2:`Tag`{`id`:"gear_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153214}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153214}), (n2:`Tag`{`id`:"fabricate_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153215}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153215}), (n2:`Tag`{`id`:"installation_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153216}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153216}), (n2:`Tag`{`id`:"physical_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153217}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153217}), (n2:`Tag`{`id`:"fixture_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153218}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153218}), (n2:`Tag`{`id`:"actuator_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153219}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153219}), (n2:`Tag`{`id`:"incorrect_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153220}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153220}), (n2:`Tag`{`id`:"prevent_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153214}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153214}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153217}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153211}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153214}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153217}) CREATE (n1)-[r:`NSUBJPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153214}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153218}) CREATE (n1)-[r:`NMOD` {`specific`:"for"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153212}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153216}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153214}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153212}) CREATE (n1)-[r:`NMOD` {`specific`:"with"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153220}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153212}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153212}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153220}) CREATE (n1)-[r:`ACL:RELCL`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153220}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153215}) CREATE (n1)-[r:`DOBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153213}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153219}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153215}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153213}) CREATE (n1)-[r:`NMOD` {`specific`:"of"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153210}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153221}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153223}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153223}), (n2:`Tag`{`id`:"incorrectly_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153221}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153224}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153224}), (n2:`Tag`{`id`:"component_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153221}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153225}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153225}), (n2:`Tag`{`id`:"assemble_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153221}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153226}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153226}), (n2:`Tag`{`id`:"design_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153221}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153227}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153227}), (n2:`Tag`{`id`:"mistake-proof_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153227}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153227}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153227}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153226}) CREATE (n1)-[r:`NSUBJPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153225}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153224}) CREATE (n1)-[r:`NSUBJPASS`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153227}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153225}) CREATE (n1)-[r:`ADVCL` {`specific`:"so_that"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153225}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153223}) CREATE (n1)-[r:`ADVMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153221}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153228}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153231}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153231}), (n2:`Tag`{`id`:"space_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153228}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153232}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153232}), (n2:`Tag`{`id`:"product_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153228}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153233}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153233}), (n2:`Tag`{`id`:"video_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153228}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153234}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153234}), (n2:`Tag`{`id`:"shuttle_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153228}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153235}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153235}), (n2:`Tag`{`id`:"33-second_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153228}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153236}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153236}), (n2:`Tag`{`id`:"This 4-minute_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153228}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153237}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153237}), (n2:`Tag`{`id`:"program_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153228}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153238}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153238}), (n2:`Tag`{`id`:"Process Control Focus Group_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153232}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153232}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153233}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153236}) CREATE (n1)-[r:`DET`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153233}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153236}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153233}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153235}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153232}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153238}) CREATE (n1)-[r:`COP`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153232}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153238}) CREATE (n1)-[r:`DET`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153237}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153238}) CREATE (n1)-[r:`CASE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153237}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153238}) CREATE (n1)-[r:`DET`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153237}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153231}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153237}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153234}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153232}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153237}) CREATE (n1)-[r:`NMOD` {`specific`:"of"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153232}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153238}) CREATE (n1)-[r:`CC`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153232}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153238}) CREATE (n1)-[r:`CONJ` {`specific`:"and"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153228}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153242}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153242}), (n2:`Tag`{`id`:"assembly_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153243}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153243}), (n2:`Tag`{`id`:"mechanical_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153244}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153244}), (n2:`Tag`{`id`:"inspection_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153245}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153245}), (n2:`Tag`{`id`:"flight_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153246}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153246}), (n2:`Tag`{`id`:"clearly_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153247}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153247}), (n2:`Tag`{`id`:"failure_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153248}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153248}), (n2:`Tag`{`id`:"assembly_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153249}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153249}), (n2:`Tag`{`id`:"prevent_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153250}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153250}), (n2:`Tag`{`id`:"design_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153251}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153251}), (n2:`Tag`{`id`:"evident_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153252}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153252}), (n2:`Tag`{`id`:"cause_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153253}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153253}), (n2:`Tag`{`id`:"incorrect_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153254}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153254}), (n2:`Tag`{`id`:"error_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153255}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153255}), (n2:`Tag`{`id`:"mistake-proofed_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153256}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153256}), (n2:`Tag`{`id`:"critical_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153258}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153258}), (n2:`Tag`{`id`:"unless_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153259}) CREATE (n1)-[r:`SENTENCE_TAG_OCCURRENCE`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153259}), (n2:`Tag`{`id`:"initial_en"}) CREATE (n1)-[r:`TAG_OCCURRENCE_TAG`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153252}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153252}) CREATE (n1)-[r:`ROOT`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153255}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153258}) CREATE (n1)-[r:`MARK`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153250}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153243}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153255}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153250}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153249}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153250}) CREATE (n1)-[r:`NSUBJ:XSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153252}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153255}) CREATE (n1)-[r:`ADVCL` {`specific`:"unless"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153255}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153249}) CREATE (n1)-[r:`XCOMP`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153242}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153253}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153249}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153242}) CREATE (n1)-[r:`DOBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153254}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153248}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153251}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153254}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153252}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153254}) CREATE (n1)-[r:`NSUBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153251}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153246}) CREATE (n1)-[r:`ADVMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153254}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153251}) CREATE (n1)-[r:`ACL:RELCL`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153244}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153259}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153251}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153244}) CREATE (n1)-[r:`NMOD` {`specific`:"from"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153247}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153256}) CREATE (n1)-[r:`AMOD`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153247}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153245}) CREATE (n1)-[r:`COMPOUND`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153252}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153247}) CREATE (n1)-[r:`DOBJ`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153240}) CREATE (n1)-[r:`CONTAINS_SENTENCE`]->(n2);
MATCH (n1:`Lesson`{`name`:1760}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153113}) CREATE (n1)-[r:`HAS_ANNOTATED_TEXT`]->(n2);
MATCH (n:`UNIQUE IMPORT LABEL`)  WITH n LIMIT 20000 REMOVE n:`UNIQUE IMPORT LABEL` REMOVE n.`UNIQUE IMPORT ID`;
DROP CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT node.`UNIQUE IMPORT ID` IS UNIQUE;
